# Generated by Django 3.2 on 2022-05-16 17:27

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import project.utils.slug
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, verbose_name='Website or social media profile')),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, height_field='image_height', null=True, upload_to='presenters/', verbose_name='Image', width_field='image_width')),
                ('image_height', models.PositiveIntegerField(editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(editable=False, null=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('slug', project.utils.slug.EnglishAutoSlugField(blank=True, editable=False, overwrite=True, populate_from=['name'])),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('G', 'General'), ('T', 'Talk'), ('P', 'Performance'), ('S', 'Side event'), ('H', 'Hosting')], max_length=1, verbose_name='Type')),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, height_field='image_height', null=True, upload_to='activities/', verbose_name='Image', width_field='image_width')),
                ('image_height', models.PositiveIntegerField(editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(editable=False, null=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('presenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.presenter')),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PresenterTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(default='', max_length=255)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('short_bio', models.TextField(blank=True, verbose_name='Short bio')),
                ('quote', models.CharField(blank=True, max_length=255, verbose_name='Inspirational quote')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='program.presenter')),
            ],
            options={
                'verbose_name': 'presenter Translation',
                'db_table': 'program_presenter_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ActivityTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('workshopLink', models.URLField(blank=True, null=True, verbose_name='Workshop ticket')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='program.activity')),
            ],
            options={
                'verbose_name': 'activity Translation',
                'db_table': 'program_activity_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
