# Generated by Django 3.2 on 2022-05-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_auto_20200302_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
