# Generated by Django 3.2 on 2022-05-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_activity_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='duration',
        ),
    ]
