# Generated by Django 3.2 on 2022-05-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_auto_20220511_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytranslation',
            name='workshopLink',
            field=models.URLField(blank=True, null=True, verbose_name='Workshop ticket'),
        ),
    ]
