# Generated by Django 3.2 on 2022-05-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_remove_activity_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytranslation',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
