# Generated by Django 3.2 on 2022-05-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_alter_activitytranslation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='activitytranslation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activitytranslation',
            name='subtitle',
            field=models.TextField(blank=True),
        ),
    ]
