# Generated by Django 3.2 on 2022-05-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0014_alter_activity_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='link',
        ),
        migrations.AddField(
            model_name='activity',
            name='workshopLink',
            field=models.URLField(blank=True, verbose_name='Workshop ticket'),
        ),
    ]
