# Generated by Django 3.2 on 2022-05-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0015_auto_20220512_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='workshopLink',
            field=models.URLField(blank=True, null=True, verbose_name='Workshop ticket'),
        ),
    ]
