# Generated by Django 3.2 on 2022-05-12 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_auto_20220511_1352'),
        ('program', '0017_auto_20220512_1620'),
    ]

    operations = [
    ]
