# Generated by Django 3.2 on 2022-05-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20200302_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='linkedin',
            field=models.URLField(blank=True, default=None),
        ),
    ]
