<<<<<<< HEAD
# Generated by Django 3.2 on 2022-05-09 18:57
=======
# Generated by Django 3.2 on 2022-05-11 10:52
>>>>>>> 34e87411b0341d8ebfd4c28e7b2ee530bd5e6686

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20200302_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='linkedin',
            field=models.URLField(blank=True, default=None),
        ),
    ]
