# Generated by Django 3.2 on 2022-05-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_alter_partner_partner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('KP', 'Knowledge Partner'), ('PS', 'Platinum Sponsors'), ('GS', 'Grand Sponsors'), ('GCS', 'Grand Carrier Sponsors'), ('GHS', 'Grand Hospitality Sponsors'), ('SPO', 'Partners'), ('SUP', 'Supporters'), ('MP', 'Media Partners'), ('CP', 'Community Partners')], max_length=3),
        ),
    ]
