# Generated by Django 3.2 on 2022-04-03 15:23

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(default=None, upload_to='prevEventsPhotos/')),
                ('link', models.URLField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
